<nav class="navbar">
    <div class="logo">
        <img src="images/favicon.png" alt="Pets Victoria Logo" class="logo">
    </div>
    <ul>
        <li><a href="index.php">Home</a></li>
        <li><a href="add.php">Add</a></li>
        <li><a href="pets.php">Pets</a></li>
        <li><a href="gallery.php">Gallery</a></li>
    </ul>
    <div class="search-container">
        <form action="/search.php">
            <input type="text" placeholder="Search" name="search">
            <button type="submit"><span class="material-icons">search</span></button>
        </form>
    </div>
</nav>

